const types = {
    FETCHDATA: 'FETCHDATA',
    GETCLEARSTATE: 'GETCLEARSTATE',
    ONADDPRODUCT: 'ONADDPRODUCT',
    ONEDITPRODUCT: 'ONEDITPRODUCT',
    ONDELETEPRODUCT: 'ONDELETEPRODUCT',
    ONADDLOCATION: 'ONADDLOCATION',
    ONEDITLOCATION: 'ONEDITLOCATION',
    ONDELETELOCATION: 'ONDELETELOCATION',
    ONADDPURCHASE: 'ONADDPURCHASE',
    ONEDITPURCHASE: 'ONEDITPURCHASE',
    ONDELETEPURCHASE: 'ONDELETEPURCHASE',
    ONADDSALE: 'ONADDSALE',
    ONEDITSALE: 'ONEDITSALE',
    ONDELETESALE: 'ONDELETESALE',
}

export default types;