const types = {
    GETUID: 'GETUID',
    GETPROFILE: 'GETPROFILE',
    ISPROFILE: 'ISPROFILE',
    ISPRODUCT: 'ISPRODUCT',
    ISPURCHASE: 'ISPURCHASE',
    ISSALE: 'ISSALE',
    ISLOCATION: 'ISLOCATION',
    ISINVENTORY: 'ISINVENTORY',
    ONADDPRODUCT: 'ONADDPRODUCT',
    ONEDITPRODUCT: 'ONEDITPRODUCT',
    ONDELETEPRODUCT: 'ONDELETEPRODUCT',
    ONADDLOCATION: 'ONADDLOCATION',
    ONEDITLOCATION: 'ONEDITLOCATION',
    ONDELETELOCATION: 'ONDELETELOCATION',
    ONADDPURCHASE: 'ONADDPURCHASE',
    ONEDITPURCHASE: 'ONEDITPURCHASE',
    ONDELETEPURCHASE: 'ONDELETEPURCHASE',
    ONADDSALE: 'ONADDSALE',
    ONEDITSALE: 'ONEDITSALE',
    ONDELETESALE: 'ONDELETESALE',
}

export default types;